version: "3.8"

services:
  marceloanimelistapi:
    container_name: marceloanimelistapi
    image: marceloanimelistapi
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/src
    depends_on:
      - sql-server-container

  sql-server-container:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-container
    environment:
      SA_PASSWORD: "P@ssw0rd#2023"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
