version: "3.8"

services:
  marceloanimelistapi:
    container_name: marceloanimelistapi
    image: marceloanimelistapi
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/src
    depends_on:
      - postgresql-container

  postgresql-container:
    image: postgres:latest
    container_name: postgresql-container
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd#2023"
    ports:
      - "5432:5432"
